repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-toml

- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black

- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.194'
  hooks:
    - id: ruff
      # Respect `exclude` and `extend-exclude` settings.
      args: ["--force-exclude"]

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: python-use-type-annotations

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
    additional_dependencies:
    - psycopg2
    - djangorestframework
    - types-requests

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.1.1
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
