version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile.dev
    user: thierry
    volumes:
      - ./app/:/home/thierry/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
      image: postgres:14-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=thierry_dev

  cache:
    image: redis:alpine

volumes:
  postgres_data:
