FROM python:3.10-bullseye

RUN apt update \
    && apt install -y libpq-dev gcc python3-dev musl-dev libffi-dev zlib1g-dev zlib1g libjpeg-dev cargo libssl-dev netcat

RUN useradd -ms /bin/sh thierry
USER thierry
WORKDIR /home/thierry/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
RUN curl -sSL https://install.python-poetry.org | python -

ENV PATH=${PATH}:/home/thierry/.local/bin

COPY pyproject.toml ../
RUN poetry install

COPY ./app/* ./
COPY ./pytest.ini ../

ENTRYPOINT ["/home/thierry/app/script/entrypoint.dev.sh"]
