name: "Tests"

on:
  push:
    branches: [ "main", "beta", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-in-compose:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: run compose
        run: docker compose -f docker-compose.ci.yml up -d --build
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          THIERRY_SECRET: ${{ secrets.THIERRY_SECRET }}
          THIERRY_DEBUG: 1
          THIERRY_ALLOWED_HOSTS: 127.0.0.1
          THIERRY_DB_NAME: thierry_ci
          THIERRY_DB_USERNAME: postgres
          THIERRY_DB_PASSWORD: postgres
          THIERRY_DB_HOST: db
          THIERRY_DB_PORT: 5432
          THIERRY_LANG_CODE: fr-fr
          THIERRY_TZ: Europe/Paris
          DEBRIEF_ACTU_PLAYLIST_ID: PLshTqKdGwawUon5GsWo-Y4HsLgVCDnm3K

      - name: wait for app
        uses: Unsupervisedcom/action-wait-for-ports@v1.0.0
        with:
          ports: "8000"
          check-interval: 1000

      - name: test
        run: docker compose -f docker-compose.ci.yml web poetry run pytest
